-- MySQL Script generated by MySQL Workbench
-- Sun Mar 17 11:21:43 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema logdatabase
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema logdatabase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `logdatabase` DEFAULT CHARACTER SET utf8 ;
USE `logdatabase` ;

-- -----------------------------------------------------
-- Table `logdatabase`.`logcultura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logdatabase`.`logcultura` (
  `IdCultura` INT(11) NULL,
  `NomeCultura` VARCHAR(100) NULL,
  `DescricaoCultura` TEXT NULL,
  `Email` VARCHAR(50) NULL,
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Operacao` VARCHAR(1) NULL,
  `DataHoraSistema` TIMESTAMP NULL,
  `Utilizador` VARCHAR(50) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logdatabase`.`logvariavelmedida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logdatabase`.`logvariavelmedida` (
  `cultura_IdCultura` INT(11) NOT NULL,
  `variavel_IdVariavel` INT(11) NOT NULL,
  `LimiteInferior` DECIMAL(8,2) NULL,
  `LimiteSuperior` DECIMAL(8,2) NULL,
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Operacao` VARCHAR(1) NULL,
  `DataHoraSistema` TIMESTAMP NULL,
  `Utilizador` VARCHAR(50) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logdatabase`.`logmedicaoluminosidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logdatabase`.`logmedicaoluminosidade` (
  `IdMedicao` INT(11) NULL,
  `ValorMedicaoLuminosidade` DECIMAL(8,2) NULL,
  `DataHoraMedicao` TIMESTAMP NULL,
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Operacao` VARCHAR(1) NULL,
  `DataHoraSistema` TIMESTAMP NULL,
  `Utilizador` VARCHAR(50) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logdatabase`.`logsistema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logdatabase`.`logsistema` (
  `IdSistema` INT(11) NULL,
  `LimiteInferiorTemperatura` DECIMAL(8,2) NULL,
  `LimiteSuperiorTemperatura` DECIMAL(8,2) NULL,
  `LimiteInferiorLuz` DECIMAL(8,2) NULL,
  `LimiteSuperiorLuz` DECIMAL(8,2) NULL,
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Operacao` VARCHAR(1) NULL,
  `DataHoraSistema` TIMESTAMP NULL,
  `Utilizador` VARCHAR(50) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logdatabase`.`logmedicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logdatabase`.`logmedicao` (
  `NumeroMedicao` INT(11) NULL,
  `variavelmedida_cultura_IdCultura` INT(11) NULL,
  `variavelmedida_variavel_IdVariavel` INT(11) NULL,
  `DataHoraMedicao` TIMESTAMP NULL,
  `ValorMedicao` DECIMAL(8,2) NULL,
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Operacao` VARCHAR(1) NULL,
  `DataHoraSistema` TIMESTAMP NULL,
  `Utilizador` VARCHAR(50) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logdatabase`.`logmedicaotemperatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logdatabase`.`logmedicaotemperatura` (
  `IdMedicao` INT(11) NULL,
  `ValorMedicaoTemperatura` DECIMAL(8,2) NULL,
  `DataHoraMedicao` TIMESTAMP NULL,
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Operacao` VARCHAR(1) NULL,
  `DataHoraSistema` TIMESTAMP NULL,
  `Utilizador` VARCHAR(50) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logdatabase`.`logVariavel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logdatabase`.`logVariavel` (
  `IdVariavel` INT NULL,
  `NomeVariavel` VARCHAR(100) NULL,
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Operacao` VARCHAR(1) NULL,
  `DataHoraSistema` TIMESTAMP NULL,
  `Utilizador` VARCHAR(50) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logdatabase`.`logInvestigador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logdatabase`.`logInvestigador` (
  `Email` VARCHAR(50) NULL,
  `NomeInvestigador` VARCHAR(100) NULL,
  `CategoriaProfissional` VARCHAR(300) NULL,
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Operacao` VARCHAR(1) NULL,
  `DataHoraSistema` TIMESTAMP NULL,
  `Utilizador` VARCHAR(50) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logdatabase`.`logselectmedicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logdatabase`.`logselectmedicao` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `DataHoraSistema` TIMESTAMP NULL,
  `Utilizador` VARCHAR(50) NULL,
  `ClausulaWhere` VARCHAR(5000) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logdatabase`.`tabelasamigrar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logdatabase`.`tabelasamigrar` (
  `Nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Nome`))
ENGINE = InnoDB;

DELIMITER //

create procedure devolverNomeColunasTabela(IN Tabela varchar(50))
begin
	IF Tabela='logcultura' THEN
		SELECT distinct column_name FROM information_schema.columns WHERE table_schema='logdatabase' and  table_name = 'logcultura';
	ELSEIF Tabela='loginvestigador' THEN
		SELECT distinct column_name FROM information_schema.columns WHERE table_schema='logdatabase' and  table_name = 'loginvestigador';
	ELSEIF Tabela='logmedicao' THEN
		SELECT distinct column_name FROM information_schema.columns WHERE table_schema='logdatabase' and  table_name = 'logmedicao';
	ELSEIF Tabela='logmedicaoluminosidade' THEN
		SELECT distinct column_name FROM information_schema.columns WHERE table_schema='logdatabase' and  table_name = 'logmedicaoluminosidade';
	ELSEIF Tabela='logmedicaoTemperatura' THEN
		SELECT distinct column_name FROM information_schema.columns WHERE table_schema='logdatabase' and  table_name = 'logmedicaoTemperatura';
	ELSEIF Tabela='logsistema' THEN
		SELECT distinct column_name FROM information_schema.columns WHERE table_schema='logdatabase' and  table_name = 'logsistema';
	ELSEIF Tabela='logvariavel' THEN
		SELECT distinct column_name FROM information_schema.columns WHERE table_schema='logdatabase' and  table_name = 'logvariavel';
	ELSEIF Tabela='logvariavelmedida' THEN
		SELECT distinct column_name FROM information_schema.columns WHERE table_schema='logdatabase' and  table_name = 'logvariavelmedida';
	ELSEIF Tabela='logselectmedicao' THEN
		SELECT distinct column_name FROM information_schema.columns WHERE table_schema='logdatabase' and  table_name = 'logselectmedicao';
	ELSE
		signal sqlstate '45000' SET MESSAGE_TEXT ='tabela não existe';
	END IF;

end //


create procedure devolverNomeDeTabelasAMigrar()
begin
Select * from TabelasAMigrar;
end //


create procedure devolverTimestampMaximoDeTabela(IN Tabela varchar(50))
begin
IF Tabela='logcultura' THEN
    SELECT  max(DataHoraSistema) FROM logcultura;
ELSEIF Tabela='loginvestigador' THEN
    SELECT  max(DataHoraSistema) FROM loginvestigador;
ELSEIF Tabela='logmedicao' THEN
    SELECT  max(DataHoraSistema) FROM logmedicao;
ELSEIF Tabela='logmedicaoluminosidade' THEN
    SELECT  max(DataHoraSistema) FROM logmedicaoluminosidade;
ELSEIF Tabela='logmedicaotemperatura' THEN
    SELECT  max(DataHoraSistema) FROM logmedicaotemperatura;
ELSEIF Tabela='logsistema' THEN
    SELECT  max(DataHoraSistema) FROM logsistema;
ELSEIF Tabela='logvariavel' THEN
    SELECT  max(DataHoraSistema) FROM logvariavel;
ELSEIF Tabela='logvariavelmedida' THEN
    SELECT  max(DataHoraSistema) FROM logvariavelmedida;
ELSEIF Tabela='logselectmedicao' THEN
    SELECT  max(DataHoraSistema) FROM logselectmedicao;
ELSE
 signal sqlstate '45000'
        SET MESSAGE_TEXT ='tabela não existe';
END IF;
end //

delimiter ;


-- ---------------------------------------
-- Definicao de Roles / Privilegios Destino
-- ---------------------------------------

CREATE ROLE IF NOT EXISTS 'Administrador', 'Auditor', 'MigracaoLog';

GRANT SELECT, INSERT, UPDATE, DELETE ON logdatabase.logvariavel TO 'Administrador';
GRANT SELECT, INSERT, UPDATE, DELETE ON logdatabase.logcultura TO 'Administrador';
GRANT SELECT, INSERT, UPDATE, DELETE ON logdatabase.loginvestigador TO 'Administrador';
GRANT SELECT, INSERT, UPDATE, DELETE ON logdatabase.logvariavelmedida TO 'Administrador';
GRANT SELECT, INSERT, UPDATE, DELETE ON logdatabase.logmedicao TO 'Administrador';
GRANT SELECT, INSERT, UPDATE, DELETE ON logdatabase.logmedicaoluminosidade TO 'Administrador';
GRANT SELECT, INSERT, UPDATE, DELETE ON logdatabase.logmedicaotemperatura TO 'Administrador';
GRANT SELECT, INSERT, UPDATE, DELETE ON logdatabase.logsistema TO 'Administrador';
GRANT SELECT, INSERT, UPDATE, DELETE ON logdatabase.logselectmedicao TO 'Administrador';
GRANT SELECT, INSERT, UPDATE, DELETE ON logdatabase.tabelasamigrar TO 'Administrador';

GRANT SELECT ON logdatabase.logvariavel TO 'Auditor';
GRANT SELECT ON logdatabase.logcultura TO 'Auditor';
GRANT SELECT ON logdatabase.loginvestigador TO 'Auditor';
GRANT SELECT ON logdatabase.logvariavelmedida TO 'Auditor';
GRANT SELECT ON logdatabase.logmedicao TO 'Auditor';
GRANT SELECT ON logdatabase.logmedicaoluminosidade TO 'Auditor';
GRANT SELECT ON logdatabase.logmedicaotemperatura TO 'Auditor';
GRANT SELECT ON logdatabase.logsistema TO 'Auditor';
GRANT SELECT ON logdatabase.logselectmedicao TO 'Auditor';

GRANT INSERT ON logdatabase.logvariavel TO 'MigracaoLog';
GRANT INSERT ON logdatabase.logcultura TO 'MigracaoLog';
GRANT INSERT ON logdatabase.loginvestigador TO 'MigracaoLog';
GRANT INSERT ON logdatabase.logvariavelmedida TO 'MigracaoLog';
GRANT INSERT ON logdatabase.logmedicao TO 'MigracaoLog';
GRANT INSERT ON logdatabase.logmedicaoluminosidade TO 'MigracaoLog';
GRANT INSERT ON logdatabase.logmedicaotemperatura TO 'MigracaoLog';
GRANT INSERT ON logdatabase.logsistema TO 'MigracaoLog';
GRANT INSERT ON logdatabase.logselectmedicao TO 'MigracaoLog';



INSERT INTO tabelasamigrar(Nome) SELECT table_name from information_schema.tables where table_schema = 'logdatabase';
DELETE FROM tabelasamigrar where Nome = "tabelasamigrar";

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
