-- MySQL Script generated by MySQL Workbench
-- Sun Mar 17 09:22:02 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema maindatabase
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema maindatabase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `maindatabase` DEFAULT CHARACTER SET utf8 ;
USE `maindatabase` ;

-- -----------------------------------------------------
-- Table `maindatabase`.`investigador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maindatabase`.`investigador` (
  `Email` VARCHAR(50) NOT NULL,
  `NomeInvestigador` VARCHAR(100) NOT NULL,
  `CategoriaProfissional` VARCHAR(300) NULL,
  PRIMARY KEY (`Email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maindatabase`.`cultura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maindatabase`.`cultura` (
  `IdCultura` INT(11) NOT NULL AUTO_INCREMENT,
  `NomeCultura` VARCHAR(100) NOT NULL,
  `DescricaoCultura` TEXT NULL,
  `Email` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`IdCultura`),
  INDEX `fk_investigador_responsavel_idx` (`Email` ASC),
  CONSTRAINT `fk_investigador_responsavel`
    FOREIGN KEY (`Email`)
    REFERENCES `maindatabase`.`investigador` (`Email`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maindatabase`.`variavel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maindatabase`.`variavel` (
  `IdVariavel` INT(11) NOT NULL AUTO_INCREMENT,
  `NomeVariavel` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`IdVariavel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maindatabase`.`variavelmedida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maindatabase`.`variavelmedida` (
  `cultura_IdCultura` INT(11) NOT NULL,
  `variavel_IdVariavel` INT(11) NOT NULL,
  `LimiteInferior` DECIMAL(8,2) NOT NULL,
  `LimiteSuperior` DECIMAL(8,2) NOT NULL,
  PRIMARY KEY (`cultura_IdCultura`, `variavel_IdVariavel`),
  INDEX `fk_cultura_has_variavel_variavel1_idx` (`variavel_IdVariavel` ASC),
  INDEX `fk_cultura_has_variavel_cultura1_idx` (`cultura_IdCultura` ASC),
  CONSTRAINT `fk_cultura_variavel_medida`
    FOREIGN KEY (`cultura_IdCultura`)
    REFERENCES `maindatabase`.`cultura` (`IdCultura`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_variavel_medida`
    FOREIGN KEY (`variavel_IdVariavel`)
    REFERENCES `maindatabase`.`variavel` (`IdVariavel`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maindatabase`.`medicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maindatabase`.`medicao` (
  `NumeroMedicao` INT(11) NOT NULL AUTO_INCREMENT,
  `DataHoraMedicao` TIMESTAMP NULL,
  `ValorMedicao` DECIMAL(8,2) NOT NULL,
  `variavelmedida_cultura_IdCultura` INT(11) NOT NULL,
  `variavelmedida_variavel_IdVariavel` INT(11) NOT NULL,
  PRIMARY KEY (`NumeroMedicao`, `variavelmedida_cultura_IdCultura`, `variavelmedida_variavel_IdVariavel`),
  INDEX `fk_medicao_variavelmedida1_idx` (`variavelmedida_cultura_IdCultura` ASC, `variavelmedida_variavel_IdVariavel` ASC),
  CONSTRAINT `fk_cultura_variavel_variavelmedida`
    FOREIGN KEY (`variavelmedida_cultura_IdCultura` , `variavelmedida_variavel_IdVariavel`)
    REFERENCES `maindatabase`.`variavelmedida` (`cultura_IdCultura` , `variavel_IdVariavel`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maindatabase`.`sistema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maindatabase`.`sistema` (
  `IdSistema` INT(11) NOT NULL AUTO_INCREMENT,
  `LimiteInferiorTemperatura` DECIMAL(8,2) NOT NULL,
  `LimiteSuperiorTemperatura` DECIMAL(8,2) NOT NULL,
  `LimiteInferiorLuz` DECIMAL(8,2) NOT NULL,
  `LimiteSuperiorLuz` DECIMAL(8,2) NOT NULL,
  PRIMARY KEY (`IdSistema`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maindatabase`.`medicaoluminosidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maindatabase`.`medicaoluminosidade` (
  `IdMedicao` INT(11) NOT NULL AUTO_INCREMENT,
  `ValorMedicaoLuminosidade` DECIMAL(8,2) NULL,
  `DataHoraMedicao` TIMESTAMP NULL,
  PRIMARY KEY (`IdMedicao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maindatabase`.`medicaotemperatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maindatabase`.`medicaotemperatura` (
  `IdMedicao` INT(11) NOT NULL AUTO_INCREMENT,
  `ValorMedicaoTemperatura` DECIMAL(8,2) NULL,
  `DataHoraMedicao` TIMESTAMP NULL,
  PRIMARY KEY (`IdMedicao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maindatabase`.`logcultura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maindatabase`.`logcultura` (
  `IdCultura` INT(11) NULL,
  `NomeCultura` VARCHAR(100) NULL,
  `DescricaoCultura` TEXT NULL,
  `Email` VARCHAR(50) NULL,
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Operacao` VARCHAR(1) NULL,
  `DataHoraSistema` TIMESTAMP NULL,
  `Utilizador` VARCHAR(50) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maindatabase`.`logvariavelmedida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maindatabase`.`logvariavelmedida` (
  `cultura_IdCultura` INT(11) NOT NULL,
  `variavel_IdVariavel` INT(11) NOT NULL,
  `LimiteInferior` DECIMAL(8,2) NULL,
  `LimiteSuperior` DECIMAL(8,2) NULL,
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Operacao` VARCHAR(1) NULL,
  `DataHoraSistema` TIMESTAMP NULL,
  `Utilizador` VARCHAR(50) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maindatabase`.`logmedicaoluminosidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maindatabase`.`logmedicaoluminosidade` (
  `IdMedicao` INT(11) NULL,
  `ValorMedicaoLuminosidade` DECIMAL(8,2) NULL,
  `DataHoraMedicao` TIMESTAMP NULL,
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Operacao` VARCHAR(1) NULL,
  `DataHoraSistema` TIMESTAMP NULL,
  `Utilizador` VARCHAR(50) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maindatabase`.`logsistema` - AQUI
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maindatabase`.`logsistema` (
  `IdSistema` INT(11) NULL,
  `LimiteInferiorTemperatura` DECIMAL(8,2) NULL,
  `LimiteSuperiorTemperatura` DECIMAL(8,2) NULL,
  `LimiteInferiorLuz` DECIMAL(8,2) NULL,
  `LimiteSuperiorLuz` DECIMAL(8,2) NULL,
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Operacao` VARCHAR(1) NULL,
  `DataHoraSistema` TIMESTAMP NULL,
  `Utilizador` VARCHAR(50) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maindatabase`.`logmedicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maindatabase`.`logmedicao` (
  `NumeroMedicao` INT(11) NULL,
  `variavelmedida_cultura_IdCultura` INT(11) NULL,
  `variavelmedida_variavel_IdVariavel` INT(11) NULL,
  `DataHoraMedicao` TIMESTAMP NULL,
  `ValorMedicao` DECIMAL(8,2) NULL,
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Operacao` VARCHAR(1) NULL,
  `DataHoraSistema` TIMESTAMP NULL,
  `Utilizador` VARCHAR(50) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maindatabase`.`logmedicaotemperatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maindatabase`.`logmedicaotemperatura` (
  `IdMedicao` INT(11) NULL,
  `ValorMedicaoTemperatura` DECIMAL(8,2) NULL,
  `DataHoraMedicao` TIMESTAMP NULL,
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Operacao` VARCHAR(1) NULL,
  `DataHoraSistema` TIMESTAMP NULL,
  `Utilizador` VARCHAR(50) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maindatabase`.`logVariavel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maindatabase`.`logVariavel` (
  `IdVariavel` INT NULL,
  `NomeVariavel` VARCHAR(100) NULL,
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Operacao` VARCHAR(1) NULL,
  `DataHoraSistema` TIMESTAMP NULL,
  `Utilizador` VARCHAR(50) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maindatabase`.`logInvestigador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maindatabase`.`logInvestigador` (
  `Email` VARCHAR(50) NULL,
  `NomeInvestigador` VARCHAR(100) NULL,
  `CategoriaProfissional` VARCHAR(300) NULL,
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Operacao` VARCHAR(1) NULL,
  `DataHoraSistema` TIMESTAMP NULL,
  `Utilizador` VARCHAR(50) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maindatabase`.`logselectmedicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maindatabase`.`logselectmedicao` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `DataHoraSistema` TIMESTAMP NULL,
  `Utilizador` VARCHAR(50) NULL,
  `ClausulaWhere` VARCHAR(5000) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;

USE `maindatabase`;

DELIMITER $$

-- -------------------------------------------------
-- triggers AFTER para tabela INVESTIGADOR
-- -------------------------------------------------

USE `maindatabase`$$
CREATE DEFINER = CURRENT_USER TRIGGER `maindatabase`.`investigador_AFTER_INSERT` AFTER INSERT ON `investigador` FOR EACH ROW
BEGIN
	insert into loginvestigador(operacao,DataHoraSistema,Utilizador,Email,NomeInvestigador,CategoriaProfissional) 
	values ('I',CURRENT_TIMESTAMP,current_user(),new.email,new.nomeinvestigador,new.categoriaProfissional);
END$$

USE `maindatabase`$$
CREATE DEFINER = CURRENT_USER TRIGGER `maindatabase`.`investigador_AFTER_UPDATE` AFTER UPDATE ON `investigador` FOR EACH ROW
BEGIN
	insert into loginvestigador(operacao,DataHoraSistema,Utilizador,Email,NomeInvestigador,CategoriaProfissional) 
	values ('U',CURRENT_TIMESTAMP,current_user(),new.email,new.nomeinvestigador,new.categoriaProfissional);
END$$

USE `maindatabase`$$
CREATE DEFINER = CURRENT_USER TRIGGER `maindatabase`.`investigador_AFTER_DELETE` AFTER DELETE ON `investigador` FOR EACH ROW
BEGIN
	insert into loginvestigador(operacao,DataHoraSistema,Utilizador,Email,NomeInvestigador,CategoriaProfissional) 
	values ('D',CURRENT_TIMESTAMP,current_user(),old.email,old.nomeinvestigador,old.categoriaProfissional);
END$$

-- ---------------------------------------------
-- triggers AFTER para tabela CULTURA
-- ---------------------------------------------

USE `maindatabase`$$
CREATE DEFINER = CURRENT_USER TRIGGER `maindatabase`.`cultura_AFTER_INSERT` AFTER INSERT ON `cultura` FOR EACH ROW
BEGIN
	insert into logcultura(Operacao,DataHoraSistema,Utilizador,idCultura,NomeCultura,DescricaoCultura,Email) 
	values ('I',CURRENT_TIMESTAMP,current_user(),new.idCultura,new.nomeCultura,new.DescricaoCultura,new.Email);
END$$

USE `maindatabase`$$
CREATE DEFINER = CURRENT_USER TRIGGER `maindatabase`.`cultura_AFTER_UPDATE` AFTER UPDATE ON `cultura` FOR EACH ROW
BEGIN
	insert into logcultura(Operacao,DataHoraSistema,Utilizador,idCultura,NomeCultura,DescricaoCultura,Email) 
	values ('U',CURRENT_TIMESTAMP,current_user(),new.idCultura,new.nomeCultura,new.DescricaoCultura,new.Email);
END$$

USE `maindatabase`$$
CREATE DEFINER = CURRENT_USER TRIGGER `maindatabase`.`cultura_AFTER_DELETE` AFTER DELETE ON `cultura` FOR EACH ROW
BEGIN
	insert into logcultura(Operacao,DataHoraSistema,Utilizador,idCultura,NomeCultura,DescricaoCultura,Email) 
	values ('D',CURRENT_TIMESTAMP,current_user(),old.idCultura,old.nomeCultura,old.DescricaoCultura,old.Email);
END$$

-- -----------------------------------------
-- triggers BEFORE para tabela CULTURA
-- -----------------------------------------

USE `maindatabase`$$
CREATE DEFINER = CURRENT_USER TRIGGER `maindatabase`.`cultura_BEFORE_UPDATE` BEFORE UPDATE ON `cultura` FOR EACH ROW
BEGIN
	DECLARE t_rows INT;
	DECLARE MESSAGE_TEXT varchar(100);

	SELECT count(*) into t_rows from mysql.user where user=REPLACE(current_user(), '@localhost', '') and super_priv="Y";

    if (t_rows<1) then
	    signal sqlstate '45000'
        SET MESSAGE_TEXT ='não tem permiçoes para mexer nesta tabela';
	end if;
END$$

USE `maindatabase`$$
CREATE DEFINER = CURRENT_USER TRIGGER `maindatabase`.`cultura_BEFORE_INSERT` BEFORE INSERT ON `cultura` FOR EACH ROW
BEGIN
	DECLARE t_rows INT;
	DECLARE MESSAGE_TEXT varchar(100);

	SELECT count(*) into t_rows from mysql.user where user=REPLACE(current_user(), '@localhost', '') and super_priv="Y";

    if (t_rows<1) then
	    signal sqlstate '45000'
        SET MESSAGE_TEXT ='não tem permiçoes para mexer nesta tabela';
	end if;
END$$
	
USE `maindatabase`$$
CREATE DEFINER = CURRENT_USER TRIGGER `maindatabase`.`cultura_BEFORE_DELETE` BEFORE DELETE ON `cultura` FOR EACH ROW
BEGIN
	DECLARE t_rows INT;
	DECLARE MESSAGE_TEXT varchar(100);

	SELECT count(*) into t_rows from mysql.user where user=REPLACE(current_user(), '@localhost', '') and super_priv="Y";

    if (t_rows<1) then
	    signal sqlstate '45000'
        SET MESSAGE_TEXT ='não tem permiçoes para mexer nesta tabela';
	end if;
END$$

-- ---------------------------------------
-- triggers AFTER para tabela VARIAVEL
-- ---------------------------------------

USE `maindatabase`$$
DROP TRIGGER IF EXISTS `variavel_AFTER_UPDATE`$$
CREATE DEFINER = CURRENT_USER TRIGGER `maindatabase`.`variavel_AFTER_UPDATE` AFTER UPDATE ON `variavel` FOR EACH ROW
BEGIN
	insert into logvariavel(Operacao,DataHoraSistema,Utilizador,IdVariavel,NomeVariavel) 
	values ('U',CURRENT_TIMESTAMP,current_user(),new.IdVariavel,new.NomeVariavel);
END$$

USE `maindatabase`$$
DROP TRIGGER IF EXISTS `variavel_AFTER_INSERT`$$
CREATE DEFINER = CURRENT_USER TRIGGER `maindatabase`.`variavel_AFTER_INSERT` AFTER INSERT ON `variavel` FOR EACH ROW
BEGIN
	insert into logvariavel(Operacao,DataHoraSistema,Utilizador,IdVariavel,NomeVariavel) 
	values ('I',CURRENT_TIMESTAMP,current_user(),new.IdVariavel,new.NomeVariavel);
END$$

USE `maindatabase`$$
DROP TRIGGER IF EXISTS `variavel_AFTER_DELETE`$$
CREATE DEFINER = CURRENT_USER TRIGGER `maindatabase`.`variavel_AFTER_DELETE` AFTER DELETE ON `variavel` FOR EACH ROW
BEGIN
	insert into logvariavel(Operacao,DataHoraSistema,Utilizador,IdVariavel,NomeVariavel) 
	values ('D',CURRENT_TIMESTAMP,current_user(),old.IdVariavel,old.NomeVariavel);
END$$

-- -----------------------------------------------
-- triggers AFTER para tabela VARIAVELMEDIDA
-- -----------------------------------------------

USE `maindatabase`$$
CREATE DEFINER = CURRENT_USER TRIGGER `maindatabase`.`variavelmedida_AFTER_UPDATE` AFTER UPDATE ON `variavelmedida` FOR EACH ROW
BEGIN
	insert into logvariavelmedida(Operacao,DataHoraSistema,Utilizador,LimiteInferior,LimiteSuperior,variavel_IdVariavel,cultura_IdCultura) 
	values ('U',CURRENT_TIMESTAMP,current_user(),new.LimiteInferior,new.LimiteSuperior,new.variavel_IdVariavel,new.cultura_IdCultura);
END$$

USE `maindatabase`$$
CREATE DEFINER = CURRENT_USER TRIGGER `maindatabase`.`variavelmedida_AFTER_INSERT` AFTER INSERT ON `variavelmedida` FOR EACH ROW
BEGIN
	insert into logvariavelmedida(Operacao,DataHoraSistema,Utilizador,LimiteInferior,LimiteSuperior,variavel_IdVariavel,cultura_IdCultura) 
	values ('I',CURRENT_TIMESTAMP,current_user(),new.LimiteInferior,new.LimiteSuperior,new.variavel_IdVariavel,new.cultura_IdCultura);
END$$

USE `maindatabase`$$
CREATE DEFINER = CURRENT_USER TRIGGER `maindatabase`.`variavelmedida_AFTER_DELETE` AFTER DELETE ON `variavelmedida` FOR EACH ROW
BEGIN
	insert into logvariavelmedida(Operacao,DataHoraSistema,Utilizador,LimiteInferior,LimiteSuperior,variavel_IdVariavel,cultura_IdCultura) 
	values ('D',CURRENT_TIMESTAMP,current_user(),old.LimiteInferior,old.LimiteSuperior,old.variavel_IdVariavel,old.cultura_IdCultura);
END$$

-- ------------------------------------------------
-- triggers BEFORE para tabela VARIAVELMEDIDA
-- ------------------------------------------------

USE `maindatabase`$$
CREATE DEFINER = CURRENT_USER TRIGGER `maindatabase`.`variavelmedida_BEFORE_INSERT` BEFORE INSERT ON `variavelmedida` FOR EACH ROW
BEGIN
	DECLARE t_rows INT;
	DECLARE MESSAGE_TEXT varchar(100);

	select count(*) into t_rows from investigador,cultura where 
	investigador.nomeinvestigador=replace(current_user(),'@localhost','') 
	and cultura.email=investigador.email and cultura.idcultura=new.cultura_IdCultura;

    if (t_rows<1) then
	signal sqlstate '45000'
        SET MESSAGE_TEXT ='não tem permissões para mexer nesta tabela';
	end if;
END$$
	
	
USE `maindatabase`$$
CREATE DEFINER = CURRENT_USER TRIGGER `maindatabase`.`variavelmedida_BEFORE_UPDATE` BEFORE UPDATE ON `variavelmedida` FOR EACH ROW
BEGIN
	DECLARE t_rows INT;
	DECLARE MESSAGE_TEXT varchar(100);

	select count(*) into t_rows from investigador,cultura where 
	investigador.nomeinvestigador=replace(current_user(),'@localhost','') 
	and cultura.email=investigador.email and cultura.idcultura=new.cultura_IdCultura;

    if (t_rows<1) then
	signal sqlstate '45000'
        SET MESSAGE_TEXT ='não tem permissões para mexer nesta tabela';
	end if;
END$$


USE `maindatabase`$$
CREATE DEFINER = CURRENT_USER TRIGGER `maindatabase`.`variavelmedida_BEFORE_DELETE` BEFORE DELETE ON `variavelmedida` FOR EACH ROW
BEGIN
	DECLARE t_rows INT;
	DECLARE MESSAGE_TEXT varchar(100);

	select count(*) into t_rows from investigador,cultura where 
	investigador.nomeinvestigador=replace(current_user(),'@localhost','') 
	and cultura.email=investigador.email and cultura.idcultura=old.cultura_IdCultura;

    if (t_rows<1) then
	signal sqlstate '45000'
        SET MESSAGE_TEXT ='não tem permissões para mexer nesta tabela';
	end if;
END$$

-- ---------------------------------------
-- triggers AFTER para tabela MEDICAO
-- ---------------------------------------

USE `maindatabase`$$
CREATE DEFINER = CURRENT_USER TRIGGER `maindatabase`.`medicao_AFTER_UPDATE` AFTER UPDATE ON `medicao` FOR EACH ROW
BEGIN
	insert into logmedicao(Operacao,DataHoraSistema,Utilizador,NumeroMedicao,DataHoraMedicao,ValorMedicao,variavelmedida_variavel_IdVariavel,variavelmedida_cultura_IdCultura) 
	values ('U',CURRENT_TIMESTAMP,current_user(),new.NumeroMedicao,new.DataHoraMedicao,new.ValorMedicao,new.variavelmedida_variavel_IdVariavel,new.variavelmedida_cultura_IdCultura);
END$$

USE `maindatabase`$$
CREATE DEFINER = CURRENT_USER TRIGGER `maindatabase`.`medicao_AFTER_INSERT` AFTER INSERT ON `medicao` FOR EACH ROW
BEGIN
	insert into logmedicao(Operacao,DataHoraSistema,Utilizador,NumeroMedicao,DataHoraMedicao,ValorMedicao,variavelmedida_variavel_IdVariavel,variavelmedida_cultura_IdCultura) 
	values ('I',CURRENT_TIMESTAMP,current_user(),new.NumeroMedicao,new.DataHoraMedicao,new.ValorMedicao,new.variavelmedida_variavel_IdVariavel,new.variavelmedida_cultura_IdCultura);
END$$

USE `maindatabase`$$
CREATE DEFINER = CURRENT_USER TRIGGER `maindatabase`.`medicao_AFTER_DELETE` AFTER DELETE ON `medicao` FOR EACH ROW
BEGIN
	insert into logmedicao(Operacao,DataHoraSistema,Utilizador,NumeroMedicao,DataHoraMedicao,ValorMedicao,variavelmedida_variavel_IdVariavel,variavelmedida_cultura_IdCultura) 
	values ('D',CURRENT_TIMESTAMP,current_user(),old.NumeroMedicao,old.DataHoraMedicao,old.ValorMedicao,old.variavelmedida_variavel_IdVariavel,old.variavelmedida_cultura_IdCultura);
END$$


-- ---------------------------------------
-- triggers BEFORE para tabela MEDICAO
-- ---------------------------------------

USE `maindatabase`$$
CREATE DEFINER = CURRENT_USER TRIGGER `maindatabase`.`medicao_BEFORE_INSERT` BEFORE INSERT ON `medicao` FOR EACH ROW
BEGIN
	DECLARE t_rows INT;
	DECLARE MESSAGE_TEXT varchar(100);

	select count(*) into t_rows from investigador,cultura where 
	investigador.nomeinvestigador=replace(current_user(),'@localhost','') 
	and cultura.email=investigador.email and cultura.idcultura=new.`variavelmedida_cultura_IdCultura`;

    if (t_rows<1) then
	signal sqlstate '45000'
        SET MESSAGE_TEXT ='não tem permissões para mexer nesta tabela';
	end if;
END$$


USE `maindatabase`$$
CREATE DEFINER = CURRENT_USER TRIGGER `maindatabase`.`medicao_BEFORE_UPDATE` BEFORE UPDATE ON `medicao` FOR EACH ROW
BEGIN
	DECLARE t_rows INT;
	DECLARE MESSAGE_TEXT varchar(100);

	select count(*) into t_rows from investigador,cultura where 
	investigador.nomeinvestigador=replace(current_user(),'@localhost','') 
	and cultura.email=investigador.email and cultura.idcultura=new.`variavelmedida_cultura_IdCultura`;

    if (t_rows<1) then
	signal sqlstate '45000'
        SET MESSAGE_TEXT ='não tem permissões para mexer nesta tabela';
	end if;
END$$

	
USE `maindatabase`$$
CREATE DEFINER = CURRENT_USER TRIGGER `maindatabase`.`medicao_BEFORE_DELETE` BEFORE DELETE ON `medicao` FOR EACH ROW
BEGIN
	DECLARE t_rows INT;
	DECLARE MESSAGE_TEXT varchar(100);

	select count(*) into t_rows from investigador,cultura where 
	investigador.nomeinvestigador=replace(current_user(),'@localhost','') 
	and cultura.email=investigador.email and cultura.idcultura=old.`variavelmedida_cultura_IdCultura`;

    if (t_rows<1) then
	signal sqlstate '45000'
        SET MESSAGE_TEXT ='não tem permissões para mexer nesta tabela';
	end if;
END$$

-- ---------------------------------------
-- triggers AFTER para tabela SISTEMA
-- ---------------------------------------

USE `maindatabase`$$
CREATE DEFINER = CURRENT_USER TRIGGER `maindatabase`.`sistema_AFTER_INSERT` AFTER INSERT ON `sistema` FOR EACH ROW
BEGIN
	insert into logsistema(Operacao,DataHoraSistema,Utilizador,IdSistema,LimiteInferiorTemperatura,LimiteSuperiorTemperatura,LimiteSuperiorLuz,LimiteInferiorLuz) 
	values ('I',CURRENT_TIMESTAMP,current_user(),new.IdSistema,new.LimiteInferiorTemperatura,new.LimiteSuperiorTemperatura,new.LimiteSuperiorLuz,new.LimiteInferiorLuz);
END$$

USE `maindatabase`$$
CREATE DEFINER = CURRENT_USER TRIGGER `maindatabase`.`sistema_AFTER_UPDATE` AFTER UPDATE ON `sistema` FOR EACH ROW
BEGIN
	insert into logsistema(Operacao,DataHoraSistema,Utilizador,IdSistema,LimiteInferiorTemperatura,LimiteSuperiorTemperatura,LimiteSuperiorLuz,LimiteInferiorLuz) 
	values ('U',CURRENT_TIMESTAMP,current_user(),new.IdSistema,new.LimiteInferiorTemperatura,new.LimiteSuperiorTemperatura,new.LimiteSuperiorLuz,new.LimiteInferiorLuz);
END$$

USE `maindatabase`$$
CREATE DEFINER = CURRENT_USER TRIGGER `maindatabase`.`sistema_AFTER_DELETE` AFTER DELETE ON `sistema` FOR EACH ROW
BEGIN
	insert into logsistema(Operacao,DataHoraSistema,Utilizador,IdSistema,LimiteInferiorTemperatura,LimiteSuperiorTemperatura,LimiteSuperiorLuz,LimiteInferiorLuz) 
	values ('D',CURRENT_TIMESTAMP,current_user(),old.IdSistema,old.LimiteInferiorTemperatura,old.LimiteSuperiorTemperatura,old.LimiteSuperiorLuz,old.LimiteInferiorLuz);
END$$

-- -------------------------------------
-- triggers BEFORE para tabela SISTEMA
-- -------------------------------------

USE `maindatabase`$$
CREATE DEFINER = CURRENT_USER TRIGGER `maindatabase`.`sistema_BEFORE_INSERT` BEFORE INSERT ON `sistema` FOR EACH ROW
BEGIN
	DECLARE NumberOfRows INT;
    DECLARE MESSAGE_TEXT varchar(100); 
    SELECT count(*) into NumberOfRows from sistema;    
    if  NumberOfRows > 0 then
        signal sqlstate '45000'
        SET MESSAGE_TEXT = 'O sistema n pode ter um conjunto de valores inseridos';
    end if;
END$$

-- ------------------------------------------------
-- triggers AFTER para tabela MEDICAOLUMINOSIDADE
-- ------------------------------------------------

USE `maindatabase`$$
CREATE DEFINER = CURRENT_USER TRIGGER `maindatabase`.`medicaoluminosidade_AFTER_UPDATE` AFTER UPDATE ON `medicaoluminosidade` FOR EACH ROW
BEGIN
	insert into logmedicaoluminosidade(Operacao,DataHoraSistema,Utilizador,DataHoraMedicao,ValorMedicaoLuminosidade,IdMedicao) 
	values ('U',CURRENT_TIMESTAMP,current_user(),new.DataHoraMedicao,new.ValorMedicaoLuminosidade,new.IdMedicao);
END$$

USE `maindatabase`$$
CREATE DEFINER = CURRENT_USER TRIGGER `maindatabase`.`medicaoluminosidade_AFTER_INSERT` AFTER INSERT ON `medicaoluminosidade` FOR EACH ROW
BEGIN
	insert into logmedicaoluminosidade(Operacao,DataHoraSistema,Utilizador,DataHoraMedicao,ValorMedicaoLuminosidade,IdMedicao) 
	values ('I',CURRENT_TIMESTAMP,current_user(),new.DataHoraMedicao,new.ValorMedicaoLuminosidade,new.IdMedicao);
END$$

USE `maindatabase`$$
CREATE DEFINER = CURRENT_USER TRIGGER `maindatabase`.`medicaoluminosidade_AFTER_DELETE` AFTER DELETE ON `medicaoluminosidade` FOR EACH ROW
BEGIN
	insert into logmedicaoluminosidade(Operacao,DataHoraSistema,Utilizador,DataHoraMedicao,ValorMedicaoLuminosidade,IdMedicao) 
	values ('D',CURRENT_TIMESTAMP,current_user(),old.DataHoraMedicao,old.ValorMedicaoLuminosidade,old.IdMedicao);
END$$

-- -----------------------------------------------
-- triggers AFTER para tabela MEDICAOTEMPERATURA
-- -----------------------------------------------

USE `maindatabase`$$
CREATE DEFINER = CURRENT_USER TRIGGER `maindatabase`.`medicaotemperatura_AFTER_UPDATE` AFTER UPDATE ON `medicaotemperatura` FOR EACH ROW
BEGIN
	insert into logmedicaotemperatura(Operacao,DataHoraSistema,Utilizador,DataHoraMedicao,ValorMedicaoTemperatura,IdMedicao) 
	values ('U',CURRENT_TIMESTAMP,current_user(),new.DataHoraMedicao,new.ValorMedicaoTemperatura,new.IdMedicao);
END$$

USE `maindatabase`$$
CREATE DEFINER = CURRENT_USER TRIGGER `maindatabase`.`medicaotemperatura_AFTER_INSERT` AFTER INSERT ON `medicaotemperatura` FOR EACH ROW
BEGIN
	insert into logmedicaotemperatura(Operacao,DataHoraSistema,Utilizador,DataHoraMedicao,ValorMedicaoTemperatura,IdMedicao) 
	values ('I',CURRENT_TIMESTAMP,current_user(),new.DataHoraMedicao,new.ValorMedicaoTemperatura,new.IdMedicao);
END$$

USE `maindatabase`$$
CREATE DEFINER = CURRENT_USER TRIGGER `maindatabase`.`medicaotemperatura_AFTER_DELETE` AFTER DELETE ON `medicaotemperatura` FOR EACH ROW
BEGIN
	insert into logmedicaotemperatura(Operacao,DataHoraSistema,Utilizador,DataHoraMedicao,ValorMedicaoTemperatura,IdMedicao) 
	values ('D',CURRENT_TIMESTAMP,current_user(),old.DataHoraMedicao,old.ValorMedicaoTemperatura,old.IdMedicao);
END$$


DELIMITER ;

-- Alter table mysql.user ADD COLUMN id int not null;

-- ---------------------------
-- Stored Procedures
-- ----------------------------

DROP PROCEDURE IF EXISTS inserirNovoInvestigador;

DELIMITER $$
create procedure inserirNovoInvestigador(in InEmail varchar(500),in InNome varchar(500),IncategoriaProfe varchar(500), InPassword varchar(500))
begin
	
	Declare ExisteInvest varchar(50);
	Declare maxid int;
	Declare sqlquery varchar(100);
	
	select i.email into ExisteInvest from investigador i where i.email= InEmail;
	
		IF  ExisteInvest is null then	
			select max(id) +1 into maxid from mysql.user;
			set @sqlquery= CONCAT("CREATE USER ","'",InNome,"'","@","'localhost'","IDENTIFIED BY ","'",InPassword,"'");
			PREPARE stmt FROM @sqlquery;
			EXECUTE stmt;
		
			update mysql.user u set id=maxid where u.user = InNome;
			
			insert into Investigador values (maxid,InEmail,InNome, InCategoriaProfe);
			set @sqlqueryInvestigador_1= CONCAT("GRANT", "'Investigador' TO '",InNome,"'@'localhost'");
			PREPARE stmtInvestigador_1 FROM @sqlqueryInvestigador_1;
			EXECUTE stmtInvestigador_1;
			set @sqlqueryInvestigador_2= CONCAT("SET DEFAULT ROLE Investigador FOR '",InNome,"@'localhost'");
			PREPARE stmtInvestigador_2 FROM @sqlqueryInvestigador_2;
			EXECUTE stmtInvestigador_2;				
		ELSE
 			signal sqlstate '45000' SET MESSAGE_TEXT ='ERRO, esse email ja esta registado';
		END IF;
	
end$$




create procedure verMedicoes(in_string varchar(100))
begin
	Declare culturaid int;
	Declare datahora varchar(100);
	Declare tmpstring varchar(100);

	select substring(in_string,locate("id",in_string),locate("and",in_string)) into tmpstring;
	select ExtractNumber(tmpstring) into culturaid;
	select substring(in_string,locate("%",in_string),100) into datahora;

	select * from medicao m where m.idcultura=culturaid and m.DataHoraMedicao like datahora;
	

	insert into logselectmedicao(DataHoraSistema,utilizador,ClausulaWhere) 
	values (CURRENT_TIMESTAMP,CURRENT_USER(),in_string);

end$$





create procedure deleteMedicao(clausulaWhere varchar(100))
begin
	
	Declare Whereint int;
	Declare finalWherestring varchar(100);

if clausulaWhere = "" or clausulaWhere = " " then
	delete from medicao;
else 
	select ExtractNumber(clausulaWhere) into Whereint;
	select TRIM(TRAILING Whereint FROM clausulaWhere ) into finalWherestring; 
	select REPLACE(finalWherestring,"where","") into finalWherestring;
	select REPLACE(finalWherestring,"=","") into finalWherestring;
	select REPLACE(finalWherestring," ","") into finalWherestring;

	if finalWherestring = "variavelmedida_cultura_idcultura" then 
		delete from medicao where variavelmedida_cultura_idcultura = whereint;

	elseif finalWherestring = "variavelmedida_variavel_idvarivel" then 
		delete from medicao where variavelmedida_variavel_idvarivel  = whereint;

	elseif finalWherestring = "numeroMedicao" then 
		delete from medicao where numeroMedicao = whereint;

	elseif finalWherestring = "datahoramedicao" then 
		delete from medicao where datahoramedicao = whereint;

	elseif finalWherestring = "valormedicao" then 
		delete from medicao where valormedicao = whereint;

	else
		signal sqlstate '45000' SET MESSAGE_TEXT ='erro nos inputs';
	end if;
end if;
	
end $$





create procedure updateMedicao(clausulaSet varchar(100),clausulaWhere varchar(100))
begin
	
	Declare SETint int;
	Declare finalSetstring varchar(100);
	Declare Whereint int;
	Declare finalWherestring varchar(100);



	select ExtractNumber(clausulaSet) into SETint;
	select TRIM(TRAILING SETint FROM clausulaSet ) into finalSetstring;
	select REPLACE(finalSetstring,"set","") into finalSetstring;
	select REPLACE(finalSetstring,"=","") into finalSetstring;
	select REPLACE(finalSetstring," ","") into finalSetstring; 


if clausulaWhere = "" or clausulaWhere = " " then
	if finalSetstring= "valormedicao" then 
	UPDATE Medicao set valormedicao = SETint;
	
	elseif finalSetstring= "variavelmedida_cultura_idcultura" then 
	UPDATE Medicao set variavelmedida_cultura_idcultura = SETint;
	
	elseif finalSetstring= "variavelmedida_variavel_idvariavel" then 
	UPDATE Medicao set variavelmedida_variavel_idvariavel = SETint;

	elseif finalSetstring= "numeromedicao" then 
	UPDATE Medicao set numeromedicao = SETint;
	
	ELSE
		signal sqlstate '45000' SET MESSAGE_TEXT ='erro nos inputs';
	END IF;
else 
	select ExtractNumber(clausulaWhere) into Whereint;
	select TRIM(TRAILING Whereint FROM clausulaWhere ) into finalWherestring; 
	select REPLACE(finalWherestring,"where","") into finalWherestring;
	select REPLACE(finalWherestring,"=","") into finalWherestring;
	select REPLACE(finalWherestring," ","") into finalWherestring;

	if finalSetstring= "valormedicao" then 

		if finalWherestring = "variavelmedida_cultura_idcultura" then 
			UPDATE Medicao set valormedicao = SETint where variavelmedida_cultura_idcultura = whereint;

		elseif finalWherestring = "variavelmedida_variavel_idvariavel" then 
			UPDATE Medicao set valormedicao = SETint where variavelmedida_variavel_idvariavel = whereint;

		elseif finalWherestring = "numeromedicao" then 
			UPDATE Medicao set valormedicao = SETint where numeromedicao = whereint;

		elseif finalWherestring = "datahoramedicao" then 
			UPDATE Medicao set valormedicao = SETint where datahoramedicao = whereint;

		elseif finalWherestring = "valormedicao" then 
			UPDATE Medicao set valormedicao = SETint where valormedicao = whereint;

		else
			signal sqlstate '45000' SET MESSAGE_TEXT ='erro nos inputs';
		end if;
	
	elseif finalSetstring= "variavelmedida_cultura_idcultura" then 
	
		if finalWherestring = "variavelmedida_cultura_idcultura" then 
			UPDATE Medicao set variavelmedida_cultura_idcultura = SETint where variavelmedida_cultura_idcultura = whereint;

		elseif finalWherestring = "variavelmedida_variavel_idvariavel" then 
			UPDATE Medicao set variavelmedida_cultura_idcultura = SETint where variavelmedida_variavel_idvariavel = whereint;

		elseif finalWherestring = "numeromedicao" then 
			UPDATE Medicao set variavelmedida_cultura_idcultura = SETint where numeromedicao = whereint;

		elseif finalWherestring = "datahoramedicao" then 
			UPDATE Medicao set variavelmedida_cultura_idcultura = SETint where datahoramedicao = whereint;

		elseif finalWherestring = "valormedicao" then 
			UPDATE Medicao set variavelmedida_cultura_idcultura = SETint where valormedicao = whereint;

		else
			signal sqlstate '45000' SET MESSAGE_TEXT ='erro nos inputs';
		end if;
	
	elseif finalSetstring= "variavelmedida_variavel_idvariavel" then 
		
		if finalWherestring = "variavelmedida_cultura_idcultura" then 
			UPDATE Medicao set variavelmedida_variavel_idvariavel = SETint where variavelmedida_cultura_idcultura = whereint;

		elseif finalWherestring = "variavelmedida_variavel_idvariavel" then 
			UPDATE Medicao set variavelmedida_variavel_idvariavel = SETint where variavelmedida_variavel_idvariavel = whereint;

		elseif finalWherestring = "numeromedicao" then 
			UPDATE Medicao set variavelmedida_variavel_idvariavel = SETint where numeromedicao = whereint;

		elseif finalWherestring = "datahoramedicao" then 
			UPDATE Medicao set variavelmedida_variavel_idvariavel = SETint where datahoramedicao = whereint;

		elseif finalWherestring = "valormedicao" then 
			UPDATE Medicao set variavelmedida_variavel_idvariavel = SETint where valormedicao = whereint;

		else
			signal sqlstate '45000' SET MESSAGE_TEXT ='erro nos inputs';
		end if;
	

	elseif finalSetstring= "numeromedicao" then 
 		
		if finalWherestring = "variavelmedida_cultura_idcultura" then 
			UPDATE Medicao set numeromedicao = SETint where variavelmedida_cultura_idcultura = whereint;

		elseif finalWherestring = "variavelmedida_variavel_idvariavel" then 
			UPDATE Medicao set numeromedicao = SETint where variavelmedida_variavel_idvariavel = whereint;

		elseif finalWherestring = "numeromedicao" then 
			UPDATE Medicao set numeromedicao = SETint where numeromedicao = whereint;

		elseif finalWherestring = "datahoramedicao" then 
			UPDATE Medicao set numeromedicao = SETint where datahoramedicao = whereint;

		elseif finalWherestring = "valormedicao" then 
			UPDATE Medicao set numeromedicao = SETint where valormedicao = whereint;

		else
			signal sqlstate '45000' SET MESSAGE_TEXT ='erro nos inputs';
		end if;
	
	
	else
		signal sqlstate '45000' SET MESSAGE_TEXT ='erro nos inputs';
	end if;
END IF;
end $$



create procedure devolverEntradasPeriodoTempo(principio timestamp, fim timestamp, tabela varchar(50))
begin
-- EXEMPLO   call devolverEntradasPeriodoTempo('2019-03-10','2019-03-16',"log_variaveismedidas");
	Declare TmpPrincipio varchar(100);
	Declare Tmpfim varchar(100);
	Select CONCAT(principio,' 00:00:01') into TmpPrincipio;
	Select CONCAT(fim,' 23:59:59') into Tmpfim;
IF Tabela='logcultura' THEN
    SELECT  * FROM logcultura where dataHoraSistema BETWEEN TmpPrincipio AND Tmpfim;
ELSEIF Tabela='loginvestigador' THEN
    SELECT  * FROM loginvestigador where dataHoraSistema BETWEEN TmpPrincipio AND Tmpfim;
ELSEIF Tabela='logmedicao' THEN
    SELECT  * FROM logmedicao where dataHoraSistema BETWEEN TmpPrincipio AND Tmpfim;
ELSEIF Tabela='logmedicaoluminosidade' THEN
    SELECT  * FROM logmedicaoluminosidade where dataHoraSistema BETWEEN TmpPrincipio AND Tmpfim;
ELSEIF Tabela='logmedicaotemperatura' THEN
    SELECT  * FROM logmedicaotemperatura where dataHoraSistema BETWEEN TmpPrincipio AND Tmpfim;
ELSEIF Tabela='logsistema' THEN
    SELECT * FROM logsistema where dataHoraSistema BETWEEN TmpPrincipio AND Tmpfim;
ELSEIF Tabela='logvariavel' THEN
    SELECT  * FROM logvariavel where dataHoraSistema BETWEEN TmpPrincipio AND Tmpfim;
ELSEIF Tabela='logvariavelmedida' THEN
    SELECT * FROM logvariavelmedida where dataHoraSistema BETWEEN TmpPrincipio AND Tmpfim;
ELSEIF Tabela='logselectmedicao' THEN
    SELECT * FROM logselectmedicao where dataHoraSistema BETWEEN TmpPrincipio AND Tmpfim;
ELSE
 signal sqlstate '45000'
        SET MESSAGE_TEXT ='tabela não existe';
END IF;
end $$




DELIMITER ;

CREATE VIEW verInformacaoPessoal AS
select distinct i.email as email,i.NomeInvestigador as nome, i.categoriaProfissional as 'Categoria Profissional'
from investigador i, mysql.user u where u.user=replace(current_user(),'@localhost','') and i.nomeinvestigador=replace(current_user(),'@localhost','');


-- ---------------------------------------
-- Definicao de Roles / Privilegios Origem
-- ---------------------------------------

CREATE ROLE IF NOT EXISTS 'Administrador', 'Investigador', 'Sensor', 'Migracao';

GRANT SELECT, INSERT, UPDATE, DELETE ON maindatabase.variavel TO 'Administrador';
GRANT SELECT, INSERT, UPDATE, DELETE ON maindatabase.cultura TO 'Administrador';
GRANT SELECT, INSERT, UPDATE, DELETE ON maindatabase.investigador TO 'Administrador';
GRANT SELECT, INSERT, UPDATE, DELETE ON maindatabase.variavelmedida TO 'Administrador';
GRANT INSERT ON maindatabase.medicao TO 'Administrador';
GRANT SELECT, INSERT, UPDATE, DELETE ON maindatabase.medicaoluminosidade TO 'Administrador';
GRANT SELECT, INSERT, UPDATE, DELETE ON maindatabase.medicaotemperatura TO 'Administrador';
GRANT SELECT, INSERT, UPDATE, DELETE ON maindatabase.sistema TO 'Administrador';
GRANT SELECT, INSERT, UPDATE, DELETE ON maindatabase.logvariavel TO 'Administrador';
GRANT SELECT, INSERT, UPDATE, DELETE ON maindatabase.logcultura TO 'Administrador';
GRANT SELECT, INSERT, UPDATE, DELETE ON maindatabase.loginvestigador TO 'Administrador';
GRANT SELECT, INSERT, UPDATE, DELETE ON maindatabase.logvariavelmedida TO 'Administrador';
GRANT SELECT, INSERT, UPDATE, DELETE ON maindatabase.logmedicao TO 'Administrador';
GRANT SELECT, INSERT, UPDATE, DELETE ON maindatabase.logmedicaoluminosidade TO 'Administrador';
GRANT SELECT, INSERT, UPDATE, DELETE ON maindatabase.logmedicaotemperatura TO 'Administrador';
GRANT SELECT, INSERT, UPDATE, DELETE ON maindatabase.logsistema TO 'Administrador';
GRANT SELECT, INSERT, UPDATE, DELETE ON maindatabase.logselectmedicao TO 'Administrador';

GRANT SELECT ON maindatabase.variavel TO 'Investigador';
GRANT SELECT, INSERT, UPDATE, DELETE ON maindatabase.cultura TO 'Investigador';
GRANT SELECT, INSERT, UPDATE, DELETE ON maindatabase.variavelmedida TO 'Investigador';
GRANT INSERT ON maindatabase.medicao TO 'Investigador';
GRANT SELECT ON maindatabase.medicaoluminosidade TO 'Investigador';
GRANT SELECT ON maindatabase.medicaotemperatura TO 'Investigador';
GRANT SELECT ON maindatabase.sistema TO 'Investigador';

GRANT INSERT ON maindatabase.medicaoluminosidade TO 'Sensor';
GRANT INSERT ON maindatabase.medicaotemperatura TO 'Sensor';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
